In [ ]:
import plotly.graph_objects as go
import numpy as np

label_path = f'../data/every-layer-submission-sample/sub_vol_50.npy'
vol = np.load(label_path, allow_pickle=True)
volume = vol
print(vol.shape)
coordinates_tuples = []
for i in range(volume.shape[0]):
    for j in range(volume.shape[1]):
        for k in range(volume.shape[2]):
            if i == 0 or i == volume.shape[0] - 1 or j == 0 or j == volume.shape[1] - 1 or k == 0 or k == volume.shape[2] - 1:
                x_coord = i
                y_coord = j
                z_coord = k
                coordinates_tuples.append([x_coord, y_coord, z_coord, volume[i, j, k]])

arr = np.asarray(coordinates_tuples)
# frames.append(go.Frame(
data=go.Scatter3d(
    x=arr[:, 0], y=arr[:, 1], z=arr[:, 2],
    mode='markers',
    marker=dict(
        size=1,
        # color=np.full(arr.shape[0], k),                # set color to an array/list of desired values
        color=arr[:, 3],
        colorscale='Viridis',   # choose a colorscale
        opacity=1,
    ),
)#,
    # name=str(k) # you need to name the frame for the animation to behave properly
    # ))
                
fig = go.Figure(data=data)

fig.show()

In [ ]:
# Import data
import time
import numpy as np

# from skimage import io

label_path = f'../data/every-layer-submission-sample/sub_vol_50.npy'
vol = np.load(label_path, allow_pickle=True)
volume = vol.T
# volume = volume[:100, :100, :100]
r, c = volume[0].shape
print(vol.shape, volume.shape)
# Define frames
import plotly.graph_objects as go

nb_frames = len(np.unique(volume))

coordinates_tuples = []
for x in range(volume.shape[0]):
    for y in range(volume.shape[1]):
        for z in range(volume.shape[2]):
            x_coord = x
            y_coord = y
            z_coord = z
            coordinates_tuples.append([x_coord, y_coord, z_coord, volume[x, y, z]])

arr = np.asarray(coordinates_tuples)

frames = []
for c in range(nb_frames):
    sub_arr = arr[arr[:, 3] == c]
    frames.append(go.Frame(
        data=go.Scatter3d(
            x=sub_arr[:, 0], y=sub_arr[:, 1], z=sub_arr[:, 2],
            mode='markers',
            marker=dict(
                color=np.full(sub_arr.shape[0], c),                # set color to an array/list of desired values
                colorscale='Viridis',   # choose a colorscale
                opacity=0.8,
                cmin=0,
                cmax=nb_frames
            )
        ),
        name=str(c) # you need to name the frame for the animation to behave properly
        ))
                
fig = go.Figure(frames=frames)

# Add data to be displayed before animation starts
# fig.add_trace(go.Surface(
#     z=volume[0]
#     ))
fig.add_trace(go.Scatter3d(
    x=sub_arr[:, 0], y=sub_arr[:, 1], z=sub_arr[:, 2],
    mode='markers',
    marker=dict(
        color=np.full(sub_arr.shape[0], c),                # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8,
        cmin=0,
        cmax=nb_frames
    ),
))

def frame_args(duration):
    return {
            "frame": {"duration": duration},
            "mode": "immediate",
            "fromcurrent": True,
            "transition": {"duration": duration, "easing": "linear"},
        }

sliders = [
            {
                "pad": {"b": 10, "t": 60},
                "len": 0.9,
                "x": 0.1,
                "y": 0,
                "steps": [
                    {
                        "args": [[f.name], frame_args(0)],
                        "label": str(k),
                        "method": "animate",
                    }
                    for k, f in enumerate(fig.frames)
                ],
            }
        ]

# Layout
fig.update_layout(
         title='Slices in volumetric data',
         width=600,
         height=600,
         scene = dict(
            xaxis = dict(range=[0,100]),
            yaxis = dict(range=[0,100]),
            zaxis = dict(range=[0,100]),
            aspectratio=dict(x=1, y=1, z=1),),
         updatemenus = [
            {
                "buttons": [
                    {
                        "args": [None, frame_args(100)],
                        "label": "&#9654;", # play symbol
                        "method": "animate",
                    },
                    {
                        "args": [[None], frame_args(0)],
                        "label": "&#9724;", # pause symbol
                        "method": "animate",
                    },
                ],
                "direction": "left",
                "pad": {"r": 10, "t": 70},
                "type": "buttons",
                "x": 0.1,
                "y": 0,
            }
         ],
         sliders=sliders
)

fig.show()

In [ ]:
from torchmetrics.functional.classification import dice
import torch


preds = torch.tensor([[[0.9, 0.5, .8, .9]]])
target = torch.tensor([[[1, 1, 0, 0]]])
print(dice(preds, target, num_classes=2, threshold=0.8, multiclass=True))

preds = torch.tensor([[[0.9, 0.5, .8, .9]]])
target = torch.tensor([[[0, 0, 1, 0]]])
print(dice(preds, target, num_classes=2, threshold=0.8, multiclass=True))

preds = torch.tensor([[[0.5, 0.5, .5, .9]]])
target = torch.tensor([[[0, 0, 0, 1]]])
print(dice(preds, target, num_classes=2, threshold=0.8, multiclass=True))

In [ ]:
from torchmetrics.functional.classification import dice
import torch


preds = torch.tensor([[[0.9, 0.5, .8, .9], [0.9, 0.5, .8, .9]], [[0.5, 0.5, .5, .9], [0.5, 0.5, .5, .9]]])
target = torch.tensor([[[1, 1, 0, 0], [0, 0, 1, 0]], [[0, 0, 0, 1], [0, 0, 0, 1]]])
dice(preds, target, num_classes=2, threshold=0.8, average='macro', multiclass=True, mdmc_average='samplewise')

In [ ]:
((0.25 + 0.5) / 2 + (1  + 1) / 2 ) / 2

In [ ]:
label_path = f'../data/every-layer-submission-sample/sub_vol_50.npy'
vol = np.load(label_path, allow_pickle=True)
volume = vol
print(vol.shape)
_max = np.max(volume)
coordinates_tuples = []
for i in range(volume.shape[0]):
    for j in range(volume.shape[1]):
        for k in range(volume.shape[2]):
            if i == 0 or i == volume.shape[0] - 1 or j == 0 or j == volume.shape[1] - 1 or k == 0 or k == volume.shape[2] - 1:
                x_coord = i
                y_coord = j
                z_coord = k
                if i % 2 == 0:
                    value = _max - volume[i, j, k]
                else:
                    value = volume[i, j, k]
                coordinates_tuples.append([x_coord, y_coord, z_coord, value])

arr = np.asarray(coordinates_tuples)
# frames.append(go.Frame(
data=go.Scatter3d(
    x=arr[:, 0], y=arr[:, 1], z=arr[:, 2],
    mode='markers',
    marker=dict(
        size=1,
        # color=np.full(arr.shape[0], k),                # set color to an array/list of desired values
        color=arr[:, 3],
        colorscale='Viridis',   # choose a colorscale
        opacity=1,
    ),
)#,
    # name=str(k) # you need to name the frame for the animation to behave properly
    # ))
                
fig = go.Figure(data=data)

fig.show()

In [ ]:
label_path = f'../data/every-layer-submission-sample/sub_vol_50.npy'
vol = np.load(label_path, allow_pickle=True)
volume = vol
print(vol.shape)
_max = np.max(volume)
coordinates_tuples = []
for i in range(volume.shape[0]):
    for j in range(volume.shape[1]):
        for k in range(volume.shape[2]):
            if i == 0 or i == volume.shape[0] - 1 or j == 0 or j == volume.shape[1] - 1 or k == 0 or k == volume.shape[2] - 1:
                x_coord = i
                y_coord = j
                z_coord = k
                if j % 2 == 0:
                    value = _max - volume[i, j, k]
                else:
                    value = volume[i, j, k]
                coordinates_tuples.append([x_coord, y_coord, z_coord, value])

arr = np.asarray(coordinates_tuples)
# frames.append(go.Frame(
data=go.Scatter3d(
    x=arr[:, 0], y=arr[:, 1], z=arr[:, 2],
    mode='markers',
    marker=dict(
        size=1,
        # color=np.full(arr.shape[0], k),                # set color to an array/list of desired values
        color=arr[:, 3],
        colorscale='Viridis',   # choose a colorscale
        opacity=1,
    ),
)#,
    # name=str(k) # you need to name the frame for the animation to behave properly
    # ))
                
fig = go.Figure(data=data)

fig.show()

In [ ]:
label_path = f'../data/every-layer-submission-sample/sub_vol_50.npy'
vol = np.load(label_path, allow_pickle=True)
volume = vol
print(vol.shape)
_max = np.max(volume)
coordinates_tuples = []
for i in range(volume.shape[0]):
    for j in range(volume.shape[1]):
        for k in range(volume.shape[2]):
            if i == 0 or i == volume.shape[0] - 1 or j == 0 or j == volume.shape[1] - 1 or k == 0 or k == volume.shape[2] - 1:
                x_coord = i
                y_coord = j
                z_coord = k
                if k % 2 == 0:
                    value = _max - volume[i, j, k]
                else:
                    value = volume[i, j, k]
                coordinates_tuples.append([x_coord, y_coord, z_coord, value])

arr = np.asarray(coordinates_tuples)
# frames.append(go.Frame(
data=go.Scatter3d(
    x=arr[:, 0], y=arr[:, 1], z=arr[:, 2],
    mode='markers',
    marker=dict(
        size=1,
        # color=np.full(arr.shape[0], k),                # set color to an array/list of desired values
        color=arr[:, 3],
        colorscale='Viridis',   # choose a colorscale
        opacity=1,
    ),
)#,
    # name=str(k) # you need to name the frame for the animation to behave properly
    # ))
                
fig = go.Figure(data=data)

fig.show()

# Test postprocessing

## Initialisation des masks id

In [43]:
import numpy as np

def init_instance_volume_optimise(volume, dim):
    # Utiliser np.moveaxis pour traiter les dimensions de manière plus générique
    volume = np.moveaxis(volume, dim, 0)

    # Appliquer la logique de la fonction de manière vectorisée
    unique_values = np.unique(volume[1])
    id_instances = np.arange(len(unique_values))
    
    mask = volume[1] != 0
    instance_mapping = np.zeros_like(volume[1])
    
    for new_id, old_id in zip(id_instances, unique_values):
        instance_mapping = np.where(volume[1] == old_id, new_id, instance_mapping)

    volume[1] = np.where(mask, instance_mapping, 0)

    # Rétablir l'ordre des dimensions original
    volume = np.moveaxis(volume, 0, dim)

    return volume

def init_instance_volume(volume, dim) -> np.ndarray:
    id_instance = 0
    volume = np.moveaxis(volume, dim, 0)
    
    for i in range(volume.shape[0]):
        instance_slice = volume[i, :, :, 1]
        
        for id in np.unique(instance_slice):
            instance_slice = np.where(instance_slice == id, id_instance, instance_slice)
            id_instance += 1
        
        volume[i, :, :, 1] = instance_slice
    
    volume = np.moveaxis(volume, 0, dim)
    
    return volume

# Exemple d'utilisation
volume = np.random.randint(0, 5, (3, 4, 4, 2))

dim = 1  # ou 0 pour tester l'autre dimension
resultat_opt = init_instance_volume_optimise(volume.copy(), dim)
resultat = init_instance_volume(volume.copy(), dim)
print((resultat == resultat_opt).all())



False


In [51]:
print(resultat_opt[:, 2, :, 1])
print(resultat[:, 2, :, 1])

[[0 1 1 2]
 [1 2 0 3]
 [2 4 2 3]]
[[10 11 11 12]
 [11 12 10 13]
 [12 14 12 13]]


## Calcul du taux de recouvrement

In [80]:
# Exemple d'utilisation
tableau1 = np.array([1, 2, 1, 3, 2, 3, 4, 4, 1]*1000000)
tableau2 = np.array([10, 20, 10, 30, 20, 30, 40, 40, 40]*1000000)

In [23]:
import numpy as np

def create_id_mapper(sub_slice, sub_ref_slice, nb_mask):
    # Retrouver les masque disponible sur la slice
    mask_slice = np.unique(sub_slice).astype(np.int16)
    
    # Fusionner les deux tableaux en une seule matrice 2D
    tableau_combine = np.column_stack((sub_ref_slice, sub_slice))

    # Utiliser numpy.unique pour obtenir les valeurs uniques et leurs occurrences
    tuples_uniques, tuples_occurrences = np.unique(tableau_combine, axis=0, return_counts=True)
    valeurs_uniques, occurrences = np.unique(sub_ref_slice, return_counts=True)

    # Créer le tableau 2D avec les tuples uniques et les taux de répartition
    tuples_occurrences = tuples_occurrences.astype(np.float64)

    # Utiliser np.searchsorted pour obtenir les indices des valeurs uniques dans valeurs_uniques
    indices_occurrences = np.searchsorted(valeurs_uniques, tuples_uniques[:, 0])
    # Mettre à jour le taux de répartition avec les valeurs correspondantes
    tuples_occurrences /= occurrences[indices_occurrences]

    # Créer le dictionnaire final
    id_mapper = {}
    for val in valeurs_uniques:
        rates = np.full(nb_mask, np.nan)
        rates[mask_slice] = 0
        indices_val = np.where(tuples_uniques[:, 0] == val)
        rates[tuples_uniques[indices_val, 1]] = tuples_occurrences[indices_val]
        id_mapper[val] = rates

    return id_mapper

# Exemple d'utilisation
sub_slice = np.array([1, 2, 1, 3, 2, 3, 4, 4, 1])
sub_ref_slice = np.array([10, 20, 10, 30, 20, 30, 40, 40, 40])
nb_mask = 6

resultat = create_id_mapper(sub_slice, sub_ref_slice, nb_mask)
print(resultat)


{10: array([nan,  1.,  0.,  0.,  0., nan]), 20: array([nan,  0.,  1.,  0.,  0., nan]), 30: array([nan,  0.,  0.,  1.,  0., nan]), 40: array([       nan, 0.33333333, 0.        , 0.        , 0.66666667,
              nan])}


In [34]:
np.add(np.array([np.nan,  1.,  0.,  0.,  0., np.nan]), np.array([1,  1.,  0.,  0.,  0., np.nan]))
np.nan + 0

nan

## Unification des groupes de mask à travers les slices de référence

In [44]:
from numpy.lib.nanfunctions import _copyto, _replace_nan

def numpy_nansum(a, axis=None):
    a, mask = _replace_nan(a, 0)

    if mask is None:
        return np.sum(a, axis=axis, keepdims=False)
    mask = np.all(mask, axis=axis)
    tot = np.sum(a, axis=axis, keepdims=False)
    if np.any(mask):
        tot = _copyto(tot, np.nan, mask)
    return tot

In [33]:
import os
import numpy as np

def load_slice(slice_dir: str, slice_num: int) -> np.ndarray:
    slice_name = f"{slice_num:03}"
    slice_path = os.path.join(slice_dir, slice_name)
    
    return np.load(slice_path)

# def load_volume(volume_dir, dim: int) -> np.ndarray:
#     slice_dir = os.path.join(volume_dir, str(dim))
#     list_slice = []
#     for slice_num in range(300):
#         list_slice.append(
#             load_slice(slice_dir, slice_num)
#         )
    
#     return np.stack(list_slice)
def load_volume(volume_dir, dim: int) -> np.ndarray:
    label_path = f'../data/every-layer-submission-sample/sub_vol_50.npy'
    volume = np.load(label_path, allow_pickle=True)
    # volume = volume[:100, :100, :100]
    volume = volume[:10, :10, :10]
    # volume = volume[:5, :5, :5]

    binary_prob = np.random.rand(*volume.shape)
    volume = np.stack([binary_prob, volume], axis=-1)
    
    return volume


def init_instance_volume(volume: np.ndarray, dim: int) -> np.ndarray:
    id_instance = 0
    volume = np.moveaxis(volume, dim, 0)
    
    for i in range(volume.shape[0]):
        instance_slice = volume[i, :, :, 1]
        new_instance_slice = np.zeros(instance_slice.shape, dtype=np.float16)
        for id in np.unique(instance_slice):
            new_instance_slice = np.where(instance_slice == id, id_instance, new_instance_slice)
            id_instance += 1
        
        volume[i, :, :, 1] = new_instance_slice
        
    volume = np.moveaxis(volume, 0, dim)
    
    return volume, id_instance

    
def update_groups_masks(groups_masks, sub_slice_pred, sub_slice_ref):
    sub_slice_pred = sub_slice_pred.astype(np.int32)
    sub_slice_ref = sub_slice_ref.astype(np.int32)
    # Fusionner les deux tableaux en une seule matrice 2D
    tableau_combine = np.column_stack((sub_slice_ref, sub_slice_pred))
    # Utiliser numpy.unique pour obtenir les valeurs uniques et leurs occurrences
    unique_ref = np.unique(sub_slice_ref, return_counts=False)
    unique_pred = np.unique(sub_slice_pred, return_counts=False)
    
    groups_masks[unique_ref, unique_pred] = 0
    
    tuples_uniques, tuples_occurrences = np.unique(tableau_combine, axis=0, return_counts=True)
    groups_masks[tuples_uniques[:, 0], tuples_uniques[:, 1]] = tuples_occurrences
    groups_masks[unique_ref] = groups_masks[unique_ref] / np.nansum(groups_masks[unique_ref], axis=0)
        
    return groups_masks


def create_groups_masks(volume_pred: np.ndarray, volume_ref: np.ndarray, nb_mask_pred, nb_mask_ref) -> np.ndarray:
    groups_masks = np.full((nb_mask_ref, nb_mask_pred), np.nan, dtype=np.float16)
    for ref_idx in range(volume_ref.shape[1]):
        for pred_idx in range(volume_pred.shape[0]):
            groups_masks = update_groups_masks(groups_masks, volume_pred[pred_idx, ref_idx, :, 1], volume_ref[pred_idx, ref_idx, :, 1])
    
    return groups_masks

# Je suppose que mon volume fait X Y Z C
# X = 300 : axes des X
# Y = 300 : axes des Y
# C = 2 : probabilité binaire, instance id
def merge_volumes(run_name, volume_name):
    volume_dir = os.path.join(
        # get_config['submissions']['root'],
        run_name,
        volume_name
    )
    
    volume_0 = load_volume(volume_dir, dim=0)
    # Create a unique id for each masks of the volume
    volume_0, nb_mask_0 = init_instance_volume(volume_0, dim=0)
    
    volume_1 = load_volume(volume_dir, dim=1)
    # Create a unique id for each masks of the volume
    volume_1, nb_mask_1 = init_instance_volume(volume_1, dim=1)
    
    # Création de groupes de masque pour chaque slide de référence
    groups_masks = create_groups_masks(volume_0, volume_1, nb_mask_0, nb_mask_1)
    # Algorithme permettant de passer de goupes de masque par slice à un set de groupe de masque 
    # répertoriant de manière unique chaque id d'instance
    # masks_groups_unified = unifie_mask_groups(list_mask_groups)
    return groups_masks

list_mask_groups = merge_volumes('', '')
list_mask_groups

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan,  1., nan,  1., nan],
       [ 1., nan,  1., nan,  1., nan, nan,  1., nan, nan,  1., nan, nan,
         1., nan, nan,  1., nan, nan,  1., nan, nan,  1., nan,  1.],
       [nan,  1., nan,  1., nan,  1., nan, nan,  1., nan, nan,  1., nan,
        nan,  1., nan, nan,  1., nan, nan,  1., nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan,  1., nan, nan,  1., nan,  1., nan],
       [ 1., nan,  1., nan,  1., nan, nan,  1., nan, nan,  1., nan, nan,
         1., nan, nan,  1., nan, nan,  1., nan, nan,  1., nan,  1.],
       [nan,  1., nan,  1., nan,  1., nan, nan,  1., nan, nan,  1., nan,
        nan,  1., nan, nan,  1., nan, nan,  1., nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan,  1., nan, nan,  1., nan,  1., nan],
      

In [29]:
print(np.unique(np.isnan(list_mask_groups), return_counts=True))

(array([False,  True]), array([  752086, 36473570]))


In [38]:
list_mask_groups.shape

(30, 25)

In [39]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine

# all_mask_groups = np.concatenate(list_mask_groups)
all_mask_groups = list_mask_groups
# distance_matrix = pairwise_distances(all_mask_groups, metric='cosine', force_all_finite='allow-nan')
def custom_cosine_distance(x: np.ndarray, y: np.ndarray):
    xna = np.invert(np.isnan(x))
    x = x[xna]
    y = y[xna]
    
    yna = np.invert(np.isnan(y))
    x = x[yna]
    y = y[yna]
    
    # print(x)
    
    if len(x) == 0 or len(y) == 0 or np.all(x == 0) or np.all(y == 0):
        return 1
    # Compute cosine similarity
    distance = cosine(x, y)
    
    return distance

distance_matrix = pairwise_distances(all_mask_groups, metric=custom_cosine_distance, force_all_finite='allow-nan')

# start = 0
# for group in list_mask_groups:
#     end = start + len(group)
#     distance_matrix[start:end, start:end] = 1
#     start = end

distance_matrix

array([[0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0.,
        1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1.],
       [1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1.,
        0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1.],
       [1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1.,
        1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0.],
       [0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0.,
        1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1.],
       [1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1.,
        0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1.],
       [1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1.,
        1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0.],
       [0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0.,
        1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1.],
       [1., 0., 1., 1., 0., 1., 1., 0., 1

In [40]:
from sklearn.cluster import AgglomerativeClustering

clustering = AgglomerativeClustering(
    n_clusters=None,
    distance_threshold=0.5,
    compute_full_tree=True,
    metric='precomputed',
    linkage='average'
)
labels = clustering.fit_predict(distance_matrix)

len(np.unique(labels)), labels

(3,
 array([2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2,
        1, 0, 2, 1, 0, 2, 1, 0]))

In [42]:
volume = load_volume(None, None)
volume, nb_mask = init_instance_volume(volume, 0)
np.unique(volume[:, :, :, 1], return_counts=True)

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.]),
 array([54, 46, 60, 40, 66, 34,  1, 74, 25,  4, 78, 18,  8, 82, 10, 14, 80,
         6, 22, 76,  2, 30, 70, 39, 61]))

In [45]:
cluster_vector = np.zeros((len(np.unique(labels)), nb_mask), dtype=np.float16)
for mask_group, label in zip(all_mask_groups, labels):
    cluster_vector[label] = numpy_nansum(np.stack((cluster_vector[label], mask_group)), axis=0)
    
cluster_vector

array([[ 0., 10.,  0., 10.,  0., 10.,  0.,  0., 10.,  0.,  0.,  8.,  0.,
         0.,  6.,  0.,  0.,  4.,  0.,  0.,  2.,  0.,  0.,  0.,  0.],
       [10.,  0., 10.,  0., 10.,  0.,  0., 10.,  0.,  0., 10.,  0.,  0.,
        10.,  0.,  0., 10.,  0.,  0., 10.,  0.,  0., 10.,  0., 10.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  3.,  0.,  0.,  5.,
         0.,  0.,  7.,  0.,  0.,  9.,  0.,  0., 10.,  0., 10.,  0.]],
      dtype=float16)

In [46]:
import numpy as np
from tqdm.notebook import tqdm

max_indices = np.argmax(cluster_vector, axis=0)

# Afficher les indices
print(max_indices)

volume_consitant = volume.copy()
for instance, id in tqdm(list(enumerate(max_indices))):
    volume_consitant[:, : ,: , 1] = np.where(volume[:, : ,: , 1] == instance, id, volume_consitant[:, : ,: , 1])
unique_pred, count_pred = np.unique(volume_consitant[:, : ,: , 1], return_counts=True)
unique_pred, count_pred

[1 0 1 0 1 0 2 1 0 2 1 0 2 1 0 2 1 0 2 1 0 2 1 2 1]


  0%|          | 0/25 [00:00<?, ?it/s]

(array([0., 1., 2.]), array([181, 701, 118]))

In [ ]:
np.unique(volume_consitant[:, : ,: , 1], return_counts=True)

(array([0., 1., 2., 3., 4., 5., 6., 7., 8.]),
 array([ 49689, 111350,  71221, 179743, 196010,  53968, 140183,  57444,
        140392]))

In [48]:
def load_volume_test() -> np.ndarray:
    label_path = f'../data/every-layer-submission-sample/sub_vol_50.npy'
    volume = np.load(label_path, allow_pickle=True)
    # volume = volume[:100, :100, :100]
    volume = volume[:10, :10, :10]
    # volume = volume[:7, :7, :7]
    # binary_prob = np.random.rand(*volume.shape)
    # volume = np.stack([binary_prob, volume], axis=-1)
    
    return volume

unique, count = np.unique(load_volume_test(), return_counts=True)
len(unique), unique, count

(3, array([4, 5, 6], dtype=int8), array([118, 701, 181]))

In [ ]:
np.sort(count_pred) == np.sort(count)

array([False, False, False, False, False, False,  True, False, False,
       False,  True,  True,  True,  True, False])